name: Build Action with Secrets

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build action with embedded token
      env:
        MONDAY_API_TOKEN: ${{ secrets.MONDAY_API_TOKEN }}
      run: |
        # Use ncc to bundle all dependencies into a single file
        npx ncc build index.js -o dist --source-map
        
        # Replace the placeholder with the actual token
        sed -i "s/process.env.MONDAY_API_TOKEN/'$MONDAY_API_TOKEN'/g" dist/index.js
        
    - name: Commit built action
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add dist/index.js
        git commit -m "Build action with embedded Monday API token" || exit 0
        git push origin main
