name: Release Action

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## Changes in this Release
            
            - Updated Monday.com task integration
            - Improved PR parsing and task ID extraction
            - Enhanced error handling and logging
            
            ## Usage
            
            ```yaml
            - name: Update Monday.com tasks
              uses: igoroctaviano/gh-monday-actions@${{ github.ref_name }}
              with:
                commit_range: ${{ github.event.inputs.commit_range }}
                version: ${{ github.event.inputs.version }}
                environment: ${{ github.event.inputs.environment }}
                description: ${{ github.event.inputs.description }}
                monday_column_name: ${{ github.event.inputs.monday_column_name }}
                monday_api_token: ${{ secrets.MONDAY_API_TOKEN }}
            ```
          draft: false
          prerelease: false
